version: '3'

services:
  indoor-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true  # Required for GPIO access
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # For SDS011 sensor
      - "/dev/gpiomem:/dev/gpiomem"  # For GPIO access (DHT22)
    volumes:
      - ./config.ini:/app/config.ini  # Mount config file
    networks:
      - monitoring-network
    dns:
      - 192.168.1.46

  # Your existing containers (commented out since you said they're already set up)
  # influxdb:
  #   image: influxdb:2.0
  #   volumes:
  #     - influxdb-data:/var/lib/influxdb2
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_MODE=setup
  #     - DOCKER_INFLUXDB_INIT_USERNAME=admin
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
  #     - DOCKER_INFLUXDB_INIT_ORG=smbirch
  #     - DOCKER_INFLUXDB_INIT_BUCKET=indoorweather
  #   networks:
  #     - monitoring-network
  #
  # grafana:
  #   image: grafana/grafana:latest
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - monitoring-network
  #   depends_on:
  #     - influxdb

networks:
  monitoring-network:
    driver: bridge

# volumes:
#   influxdb-data:
#   grafana-data: